name: Rust

on:
  push:
    tags:
      - "v*.*.*"

env:
  CARGO_TERM_COLOR: always
  BIN_NAME: target/release/packard

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Build release
        run: cargo build --release

      - name: Upload release assets
        uses: softprops/action-gh-release@v2
        with:
          files: ${{ env.BIN_NAME }}
